# Generated by Django 4.1.6 on 2023-02-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, upload_to='menu_images/%Y/%M/%D', verbose_name='Изображение'),
        ),
    ]
