# Generated by Django 4.1.6 on 2023-02-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_menuitem_delete_menu_alter_order_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15000, verbose_name='Цена'),
        ),
    ]
